### ISSUE TITLE
How many computational resources are required during training?

### ISSUE THREAD

**Issue by picksh** [Andrew-Brown1/E2EVE#2]
Hi, thanks for your good work!

I would like to ask how many computational resources are required during training? To be more specific, what is the type and amout of GPUs that you use during training? And how much time does the training process last?

**Comment by Andrew-Brown1** [comment]
Hi there - thanks for your interest.

So all experiments used 32 V100's with a batch size of 16 on each. We trained for around 300K iterations, taking about 2 days. For the smaller datasets (FFHQ), we trained for less time

The code is also coming soon by the way - I have unfortunately been very busy with CVPR and my thesis
