### ISSUE TITLE
Missing dataset.

### ISSUE THREAD

**Issue by haizhu12** [Andrew-Brown1/E2EVE#4]
Hello This error occurs when running your code, the train.txt is missing, can you provide the corresponding data, thanks.
![QQ截图20221009122739](https://user-images.githubusercontent.com/93024130/194738175-352c858f-51e9-4476-be4d-8e264239db85.png)

**Comment by Andrew-Brown1** [comment]
Hi - thank you for raising this issue, I am on vacation currently and will be able to advise on this in about 2 weeks. Sorry for the delay

**Comment by Andrew-Brown1** [comment]
Hi - sorry for the late reply to this. 

You are right, there were missing files. I have updated the zipped file and config files in the latest commit. The zip file downloaded using "./utils/download_val_meta.sh" now contains the missing files. The latest commit also changes the path to these files in the configs.
