### ISSUE TITLE
miss train.txt

### ISSUE THREAD

**Issue by haizhu12** [Andrew-Brown1/E2EVE#5]
Hello This error occurs when running your code, the train.txt is missing, can you provide the corresponding data, thanks.
![22](https://user-images.githubusercontent.com/93024130/196185926-a3ae63f3-bd8a-4c33-a9cc-291013d4ef53.png)

**Comment by Andrew-Brown1** [comment]
Hi - thank you for raising this issue, I am on vacation currently and will be able to advise on this in about 2 weeks. Sorry for the delay

**Comment by Andrew-Brown1** [comment]
This is answered here:

https://github.com/Andrew-Brown1/E2EVE/issues/4#issuecomment-1315704302
