### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by simasima121** [Andrew-Brown1/E2EVE#6]
Hi

Will you be releasing a pre-trained model for inference?

Thanks!

**Comment by Andrew-Brown1** [comment]
Hi there, 

Yes, in November I plan on releasing some inference code along with a pre-trained model. 

Bear in mind that currently we are only permitted to release the model trained on LSUN bedroom.

Andrew

**Comment by simasima121** [comment]
Awesome, thank you
